### ISSUE TITLE
Master contains a new changes, bump to 0.0.6?

### ISSUE THREAD

**Issue by tomijarvi** [andersinno/hayes#8]
The master has a couple of new commits and I need the change where the Hayes accept also `six` versions which are newer than 1.9.0. @suutari-ai or @jaywink can you bump this to version 0.0.6?

**Comment by suutari-ai** [comment]
Cleaned up the master a bit and added release 0.1.0. Not yet in PyPI, since I don't have rights to upload hayes to PyPI. Asked @akx for PyPI rights...

**Comment by suutari-ai** [comment]
I got the PyPI permissions from @akx. (Thanks @akx!) The 0.1.0 release is now uploaded to PyPI too.
